services:
  postgres:
    image: postgres:16-alpine
    container_name: movies-postgres
    environment:
      POSTGRES_DB: moviesdb
      POSTGRES_USER: userPostgres
      POSTGRES_PASSWORD: d9tGG8jpcKC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: movies-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dacostadesarrollo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: VePVEp7bvpz
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: